name: duckling service on VM
on: [pull_request]

jobs:
  vm-job:
    runs-on: ubuntu-latest

    services:
      duckling:
        image: rasa/duckling
        ports:
        # Maps port 8000 on service container to the host
        - 8000:8000
        # Set health checks to wait until duckling has started
        # https://blog.couchbase.com/docker-health-check-keeping-containers-healthy/
        options: >-
          --health-cmd "curl --fail http://localhost:8000/ || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v1

    - name: run a health check
      run: |
        curl -X GET http://localhost:8000/
